### ISSUE TITLE
Make all exceptions in the Nominator logged (`scope(failure) assert(0)`)

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#625] opened 2020-03-05 01:45 UTC
The SCP API methods need to be `nothrow` because throwing D exceptions back to C++ code might lead to issues. There was some compiler support work on supporting exceptions being thrown across language barriers, but I don't know the latest state of things (CC @Geod24).

Note that `assert(0)` will actually throw an AssertError in non-release mode, which means we do end up throwing exceptions across language barriers anyway..

For now it would be good to at least log these exceptions.

**Comment by Geod24** [comment] 2020-03-05 06:50
> throwing D exceptions back to C++ code might lead to issues

If they pass through, it *should* work. If there's a `catch` in the C++ code, roll a dice.
In general, catching exceptions from C++ in D works, throwing exceptions for C++ to catch would need some work (https://github.com/dlang/dmd/pull/8743), but if it *just* pass through, it *should* work (or more precisely: there is no reason it should not work, but I would check if RAII works).

But otherwise... Yes to the issue.

**Comment by Geod24** [comment] 2020-07-05 04:10
Duplicate of #363

**Closed as completed by Geod24** 2020-07-05 04:10 UTC
Labels: res-duplicate
