### ISSUE TITLE
The replace and cancel functions for pending transactions are required.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#2090] opened 2021-05-14 01:41 UTC
Wallet's requirements include the following. The functionality required to implement this must be implemented in Agora.

The replace button sends the user to the ​Send BOA​ page, attempting to create the same transaction, but with a higher fee. The same rules as for a regular transaction apply (the users need to provide all required seeds). The cancel button sends the user to the ​Send BOA​ page but instead attempts to create a transaction to oneself, essentially creating a double-spend to cancel the already-propagated transaction.
When a transaction is replaced or canceled, both transactions stay present in the pending transaction until one of them gets confirmed. In general, the list of pending transactions should handle double-spend gracefully, and remove any transaction that is shown as pending if another transaction that invalidates it is accepted in a block.

**Comment by Geod24** [comment] 2021-05-14 01:49
>  The functionality required to implement this must be implemented in Agora.

That would be https://github.com/bosagora/agora/pull/1881

**Comment by Geod24** [comment] 2021-05-18 01:15
Duplicate of #245

**Closed as completed by Geod24** 2021-05-18 01:15 UTC
Labels: res-duplicate
