### ISSUE TITLE
When running on the docker, no blocks above height 19 are created.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#1552] opened 2021-01-26 02:06 UTC
I tested in the following environment.
The height of the block is not greater than 19. 
I think this phenomenon may be related to the `validator_cycle`.
I attached the log of Agora nodes as a result.

### **Basic Infomation**
**Agora**
_git address_
https://github.com/MichaelKim20/agora
_branch_
localtest

**Stoa**
_git address_
https://github.com/MichaelKim20/stoa
_branch_
test-101

**BOA-SDK-TS**
_git address_
https://github.com/MichaelKim20/boa-sdk-ts
_branch_
localtest5

### **Clone & Install**
git clone https://github.com/MichaelKim20/agora
cd agora
git checkout localtest

git submodule update --init
docker build . -t agora

git clone https://github.com/MichaelKim20/stoa
cd stoa
git checkout test-101
npm install

git clone https://github.com/MichaelKim20/boa-sdk-ts
cd boa-dk-ts
git checkout localtest5
npm install

### **Test**
**Run Agora** 
cd localtest
./drm.sh
compose up

**Run Stoa**
npm start -- -c conf/config.yaml

**Run Stoa**
npm run sendtx

### Result
This is a log of Agora
https://gist.github.com/MichaelKim20/f52ad19dbc4cb16809c51a0e963db6cb

**Comment by kchulj** [comment] 2021-01-26 05:47
Based on the log, the nodes have already retrieved block 19. But why do they try again? It fails after 25 attempts.

**Comment by kchulj** [comment] 2021-04-08 14:01
The bug is now reproducible in live production.
What could be possible causes for this? This happens after the enrollments have been accepted.

**Comment by AndrejMitrovic** [comment] 2021-04-08 14:41
Can we get the logs of all the nodes from start up to the point they get stuck?

**Comment by AndrejMitrovic** [comment] 2021-04-08 14:54
I do think I find a bug in the block retrieval though, but I'm not sure if this is the cause of the stalls. I'll submit a PR soon.

**Comment by kchulj** [comment] 2021-04-08 14:59
> Can we get the logs of all the nodes from start up to the point they get stuck?

[Here](https://gist.github.com/kchulj/d96f56f697c0d0f35d67a6d4197cec9c) is a quick overview of the logs.
From the start to this point, there is nothing interesting. I will check again whether the logs look similar for all the nodes (I think they do).

**Comment by AndrejMitrovic** [comment] 2021-04-08 15:13
Maybe try seeing if you can revert some of the changes here: https://github.com/bosagora/agora/commit/07976289832ecd2245f5ccf0abd9be8624c9ea14#diff-2c5fcbf7251215d5e7aba3eaa09c23da9d88c3645e5c278b9ef351b9798184f7

It looks suspicious to me.

**Comment by AndrejMitrovic** [comment] 2021-04-08 15:13
Though honestly I don't know why this issue always seems to occur at height 20. It's very odd.

**Comment by Geod24** [comment] 2021-04-08 16:57
The validator cycle is 20

**Comment by ferencdg** [comment] 2021-04-09 00:17
Aren't we supposed to see Enrollments in the block header at block 19(for the new cycle)?

08 10:09:21 na-001 docker[2394856]: 2021-04-08 10:09:21,664 Info [agora.consensus.protocol.Nominator] - Externalized consensus data set at 19: { tx_set: [0xb330...924e], enrolls: [], missing_validators: [], time_offset: 8417358 }

**Comment by hewison-chris** [comment] 2021-04-09 00:27
When using our Test GenesisBlock:-
Block 0 (Genesis) has the enrollments for active validators in externalizing blocks 1 -> 20.
Block 20 has the enrollments for active validators in externalizing blocks 21 -> 40.

**Comment by hewison-chris** [comment] 2021-04-09 00:30
I think the problem is due to an out by one error which will be solved after we complete the changes to using `distance` to equal to block `height` as much of the complex code related to heights and distance from enrollment will be simplified.

**Comment by omerfirmak** [comment] 2021-04-10 12:31
While testing for the `eventcore` leak, I was able to reach heights greater than 20 with no problem. I was running the nodes locally.

**Comment by kchulj** [comment] 2021-04-15 06:32
With the local faucet, I am also able to reach over 20 blocks...

**Comment by Geod24** [comment] 2021-04-22 08:58
The root cause of this issue was the various OB1 errors when it came to enrollment. This has been fixed.
Testing the fix proved difficult for two reasons:
- Our combineCandidate is a bit too simple (#1988);
- Our nomination timer was waaaaaayyyyyyy too low (#1989 & #2009);

Now that those OB1 issues have been addressed, and we have #2009, this should be fixed.

**Closed as completed by Geod24** 2021-04-22 08:58 UTC
Labels: type-bug, C.Blockchain
