### ISSUE TITLE
A too large number appears when retrieving blocks from NetworkManager

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#1338] opened 2020-11-09 09:13 UTC
I used `docker-compose up` on the local computer.
I sent the transaction and made it up to the block height of 19. I sent another 8 transactions to make the height 20.
After the agreement was completed, in the process of transferring blocks, I saw a large number in the log.
And it stopped working.

<img width="1291" alt="" src="https://user-images.githubusercontent.com/11639939/98520911-182e1e80-22b6-11eb-9f3d-5ee753fc23b0.png">

[node-2_1.log](https://github.com/bpfkorea/agora/files/5509271/node-2_1.log)
[node-3_1.log](https://github.com/bpfkorea/agora/files/5509281/node-3_1.log)
[node-4_1.log](https://github.com/bpfkorea/agora/files/5509283/node-4_1.log)
[node-5_1.log](https://github.com/bpfkorea/agora/files/5509284/node-5_1.log)
[node-6_1.log](https://github.com/bpfkorea/agora/files/5509280/node-6_1.log)
[node-7_1.log](https://github.com/bpfkorea/agora/files/5509282/node-7_1.log)

**Comment by AndrejMitrovic** [comment] 2020-11-09 09:20
Seems to be a duplicate of https://github.com/bpfkorea/agora/issues/1337. I'll close it.

**Closed as completed by AndrejMitrovic** 2020-11-09 09:20 UTC
