### ISSUE TITLE
Nominator propose an ever-growing similar list of txs without merging them

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1988] opened 2021-04-19 06:15 UTC
```
Apr 19 06:12:43 na-001 docker[2998416]: 2021-04-19 06:12:43,348 Trace [agora.node.Ledger] - Going to nominate current time offset [9353563] or newer. Genesis timestamp is [1609459200]
2021-04-19 06:09:46,26 Info [agora.consensus.protocol.Nominator] - Starting nominating timer..
2021-04-19 06:09:47,44 Info [agora.consensus.protocol.Nominator] - Nominating { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353387 } at 1618812587
2021-04-19 06:09:47,44 Info [agora.consensus.protocol.Nominator] - agora.consensus.protocol.Nominator.Nominator.nominate(): Proposing tx set for slot 1
2021-04-19 06:09:48,445 Trace [agora.consensus.protocol.Nominator] - SIGN Envelope signature 0xcaf9f3e8f8eb1b264b3ff9e7efdd429792177dd35e5cf8dfcf7eb04a161d4fcc0f76ff59b2baab3feb2817b4747da7e8aac6e15c6c4fd03ddc8b8eccd628e59a: { statement: { node: boa1xrdwryuh...5ecp, slotIndex: 1, pledge: Nominate { qset: { hash: 0x1c66...d52c, quorum: <unknown> }, votes: [{ tx_set: [0xfa25...fe02], enrolls: [], missing_validators: [], time_offset: 9353126 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2], enrolls: [], missing_validators: [], time_offset: 9353127 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff], enrolls: [], missing_validators: [], time_offset: 9353127 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485], enrolls: [], missing_validators: [], time_offset: 9353128 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d], enrolls: [], missing_validators: [], time_offset: 9353128 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353216 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353218 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353220 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353223 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353225 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353227 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353229 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353232 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353234 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353236 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353239 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353241 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353244 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353246 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353249 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353251 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353254 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353256 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353259 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353261 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353264 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353267 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353269 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353272 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353275 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353277 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353280 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x
82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353283 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353289 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353292 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353295 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353298 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353301 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353304 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353307 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353310 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353313 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353316 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353319 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353322 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353325 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353328 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353331 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353334 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353337 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353341 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353344 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353347 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353350 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353354 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353357 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353360 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353363 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353367 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353370 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353373 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353377 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353380 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353127 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353128 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353129 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353130 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353131 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5],
 enrolls: [], missing_validators: [], time_offset: 9353387 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353132 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353133 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353134 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353135 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353136 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353137 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353138 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353139 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353140 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353141 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353142 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353143 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353144 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353145 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [], time_offset: 9353146 }, { tx_set: [0xfa25...fe02, 0x5d40...bb66, 0xfc0a...4fc2, 0x82c4...93ff, 0x6eff...ea9e, 0x54e3...4485, 0xc20a...cf8d, 0x930e...66e5], enrolls: [], missing_validators: [],
```

Notice that this is not the end... The logger just ran out of buffer space (limit is 16K). It seems we are not so good at combining.

**Comment by omerfirmak** [comment] 2021-04-21 11:09
I think this is the root cause of the starvation issue here https://github.com/bosagora/agora/issues/1887#issuecomment-819446127.

Since the nominations get bigger, validating them in nomination timer takes longer and eventually dominates the whole run time.

**Comment by ferencdg** [comment] 2021-04-27 00:17
1.
The votes in the nominations are not supposed to be 'merged', each SCP message are supposed to contain the whole voting history. Those votes are only different because of the timestamp. I will modify the code to save down the timestamp before the start of the nomination, so we will have less votes.

2.
The current implementation of combineCandidates is still incorrect, it is only based on the missing validator count(which is 0 for all votes in the log...), I will fix that too soon.

3.
Even after 1 and 2 is solved it is hard to say Agora was stuck because of nomination from this log. In fact Ku said this happened during the stuck at block 19th, which had a different rootcause. So this 'endless' votes thing seems to be just a sideeffect of point 1 above.

**Closed as completed** 2021-05-04 10:16 UTC
Labels: prio-URGENT, type-bug
