### ISSUE TITLE
EnrollmentManager.createEnrollment() enters infinite loop if height == 0

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#792] opened 2020-05-06 08:05 UTC
There should be an assert so this is caught.

**Comment by linked0** [comment] 2020-06-30 00:31
This issue is not reproduced anymore because the code having the root cause has been removed by applying the `PreImageCycle`. The original code is as follows, which was in the `generatePreimages` function of the `EnrollmentManager`.

```D
ulong idx = MaxHeight;
this.preimage_rounds[idx] = hash;
for (--idx; idx >= height; --idx)
{
       hash = hashFull(hash);
       if (idx % ValidatorSet.ValidatorCycle == 0)
           this.preimage_rounds[idx] = hash;
}
```

**Comment by Geod24** [comment] 2020-07-03 09:40
Fixed by https://github.com/bpfkorea/agora/pull/815

**Closed as completed by Geod24** 2020-07-03 09:40 UTC
Labels: prio-high, type-bug
