### ISSUE TITLE
Replace non-recoverable bool return code methods with nothrow 'assert' methods

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#514] opened 2020-01-31 05:34 UTC
Per my comment in: https://github.com/bpfkorea/agora/pull/504

The example there checks if `updateEnrolledHeight` fails, and if it does it halts (assert(0)). If there is no possible recovery from `updateEnrolledHeight` returning `false`, then this method should be changed to a `void` and `nothrow` function, which halts internally on errors.

There are many more examples in our codebase. IIRC there's some in the BlockStorage too.

**Comment by Geod24** [comment] 2020-02-05 13:26
@linked0 This is a good example of what we discussed today, maybe you want to tackle this next sprint ?

**Comment by Geod24** [comment] 2020-09-08 01:37
Duplicate of #1083

**Closed as completed by Geod24** 2020-09-08 01:37 UTC
Labels: type-enhancement, C.General
