### ISSUE TITLE
`addresses_to_register` config field should be plain `string` instead of `Address`

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#2973] opened 2022-02-04 07:25 UTC
This enforces users to provide full URL and is conflicting with A/CNAME records of the DNS. DNS' A and CNAME records are just for name resolving thus a node connecting to another peer should be the decider for which interface should be accessed by default after name resolution (or should query for an URI record).

Related with #2972

**Comment by Geod24** [comment] 2022-02-04 09:42
Duplicate of https://github.com/bosagora/agora/issues/2320 ?

**Comment by mkykadir** [comment] 2022-02-04 09:46
> Duplicate of #2320 ?

Kinda, I feel explanation of that issue still directs me to provide full URL during registration (using `interface` fields) but prevent duplication by moving configuration field under `interfaces`. I think we shouldn't force users to provide full URL for registration.

**Comment by Geod24** [comment] 2022-02-04 09:47
Let's move the discussion there then.

**Closed as completed by Geod24** 2022-02-04 09:47 UTC
